const sampleFormData = [
    {
        formID: 1,
        pickupRegion: "Metro Manila",
        pickupCity: "Makati",
        pickupBarangay: "Poblacion",
        pickupStreet: "J.P. Rizal Avenue",
        pickupBuilding: "Makati Executive Tower",
        pickupDate: new Date("2024-11-07"),
        pickupTime: "7:30 AM",
        pickupPassengers: 14,
        destinationRegion: "Cavite",
        destinationCity: "Tagaytay",
        destinationBarangay: "San Jose",
        destinationBuilding: "Sky Ranch",
        departureDate: new Date("2024-11-07"),
        departureTime: "8:00 AM",
        departureAddInformation: "Private tour for a corporate group",
        deleted: false
    },
    {
        formID: 2,
        pickupRegion: "Metro Manila",
        pickupCity: "Quezon City",
        pickupBarangay: "Diliman",
        pickupStreet: "Commonwealth Avenue",
        pickupBuilding: "UP Technohub",
        pickupDate: new Date("2024-11-10"),
        pickupTime: "9:00 AM",
        pickupPassengers: 20,
        destinationRegion: "Rizal",
        destinationCity: "Antipolo",
        destinationBarangay: "San Roque",
        destinationBuilding: "Hinulugang Taktak",
        departureDate: new Date("2024-11-10"),
        departureTime: "10:00 AM",
        departureAddInformation: "School field trip",
        deleted: false
    },
    {
        formID: 3,
        pickupRegion: "Laguna",
        pickupCity: "Calamba",
        pickupBarangay: "Real",
        pickupStreet: "National Highway",
        pickupBuilding: "SM Calamba",
        pickupDate: new Date("2024-11-12"),
        pickupTime: "6:00 AM",
        pickupPassengers: 8,
        destinationRegion: "Laguna",
        destinationCity: "Los Baños",
        destinationBarangay: "Timugan",
        destinationBuilding: "Makiling Park",
        departureDate: new Date("2024-11-12"),
        departureTime: "6:30 AM",
        departureAddInformation: "Nature trip",
        deleted: false
    },
    {
        formID: 4,
        pickupRegion: "Metro Manila",
        pickupCity: "Pasay",
        pickupBarangay: "Mall of Asia Complex",
        pickupStreet: "Seaside Blvd",
        pickupBuilding: "Mall of Asia Arena",
        pickupDate: new Date("2024-11-15"),
        pickupTime: "5:00 PM",
        pickupPassengers: 50,
        destinationRegion: "Metro Manila",
        destinationCity: "Manila",
        destinationBarangay: "Intramuros",
        destinationBuilding: "Fort Santiago",
        departureDate: new Date("2024-11-15"),
        departureTime: "6:00 PM",
        departureAddInformation: "Company outing",
        deleted: false
    },
    {
        formID: 5,
        pickupRegion: "Metro Manila",
        pickupCity: "Manila",
        pickupBarangay: "Malate",
        pickupStreet: "Adriatico Street",
        pickupBuilding: "Robinsons Place",
        pickupDate: new Date("2024-11-18"),
        pickupTime: "4:00 PM",
        pickupPassengers: 6,
        destinationRegion: "Benguet",
        destinationCity: "Baguio",
        destinationBarangay: "Burnham Park",
        destinationBuilding: "Burnham Lake",
        departureDate: new Date("2024-11-18"),
        departureTime: "8:00 PM",
        departureAddInformation: "Family vacation",
        deleted: false
    }
];

module.exports = sampleFormData;
