const sampleFormData = [
    {
        formID: 1,
        pickupProvince: "Metro Manila",
        pickupCity: "Makati",
        pickupBarangay: "Poblacion",
        pickupStreet: "J.P. Rizal Avenue",
        pickupBuilding: "Makati Executive Tower",
        pickupDate: new Date("2024-11-07"),
        pickupTime: "7:30 AM",
        pickupPassengers: 14,
        departureDestination: "Tagaytay City",
        departureProvince: "Cavite",
        departureCity: "Tagaytay",
        departureBarangay: "San Jose",
        departureBuilding: "Sky Ranch",
        departureDate: new Date("2024-11-07"),
        departureTime: "8:00 AM",
        departureReturnDate: new Date("2024-11-09"),
        departureAddInformation: "Private tour for a corporate group",
        contactCompanyName: "Green Solutions Inc.",
        contactPerson: "John Doe",
        contactEmail: "johndoe@greensolutions.com",
        contactNumber: "+639123456789",
        deleted: false
    },
    {
        formID: 2,
        pickupProvince: "Metro Manila",
        pickupCity: "Quezon City",
        pickupBarangay: "Diliman",
        pickupStreet: "Commonwealth Avenue",
        pickupBuilding: "UP Technohub",
        pickupDate: new Date("2024-11-10"),
        pickupTime: "9:00 AM",
        pickupPassengers: 20,
        departureDestination: "Antipolo City",
        departureProvince: "Rizal",
        departureCity: "Antipolo",
        departureBarangay: "San Roque",
        departureBuilding: "Hinulugang Taktak",
        departureDate: new Date("2024-11-10"),
        departureTime: "10:00 AM",
        departureReturnDate: new Date("2024-11-11"),
        departureAddInformation: "School field trip",
        contactCompanyName: "Education Forward",
        contactPerson: "Maria Santos",
        contactEmail: "maria.santos@edu-forward.com",
        contactNumber: "+639987654321",
        deleted: false
    },
    {
        formID: 3,
        pickupProvince: "Laguna",
        pickupCity: "Calamba",
        pickupBarangay: "Real",
        pickupStreet: "National Highway",
        pickupBuilding: "SM Calamba",
        pickupDate: new Date("2024-11-12"),
        pickupTime: "6:00 AM",
        pickupPassengers: 8,
        departureDestination: "Los Baños",
        departureProvince: "Laguna",
        departureCity: "Los Baños",
        departureBarangay: "Timugan",
        departureBuilding: "Makiling Park",
        departureDate: new Date("2024-11-12"),
        departureTime: "6:30 AM",
        departureReturnDate: new Date("2024-11-12"),
        departureAddInformation: "Nature trip",
        contactCompanyName: "Eco Adventures",
        contactPerson: "Kevin Reyes",
        contactEmail: "kevin@ecoadventures.com",
        contactNumber: "+639223344556",
        deleted: false
    },
    {
        formID: 4,
        pickupProvince: "Metro Manila",
        pickupCity: "Pasay",
        pickupBarangay: "Mall of Asia Complex",
        pickupStreet: "Seaside Blvd",
        pickupBuilding: "Mall of Asia Arena",
        pickupDate: new Date("2024-11-15"),
        pickupTime: "5:00 PM",
        pickupPassengers: 50,
        departureDestination: "Intramuros",
        departureProvince: "Metro Manila",
        departureCity: "Manila",
        departureBarangay: "Intramuros",
        departureBuilding: "Fort Santiago",
        departureDate: new Date("2024-11-15"),
        departureTime: "6:00 PM",
        departureReturnDate: new Date("2024-11-15"),
        departureAddInformation: "Company outing",
        contactCompanyName: "Business Corp",
        contactPerson: "Clara Lim",
        contactEmail: "clara.lim@businesscorp.com",
        contactNumber: "+639112233445",
        deleted: false
    },
    {
        formID: 5,
        pickupProvince: "Metro Manila",
        pickupCity: "Manila",
        pickupBarangay: "Malate",
        pickupStreet: "Adriatico Street",
        pickupBuilding: "Robinsons Place",
        pickupDate: new Date("2024-11-18"),
        pickupTime: "4:00 PM",
        pickupPassengers: 6,
        departureDestination: "Baguio City",
        departureProvince: "Benguet",
        departureCity: "Baguio",
        departureBarangay: "Burnham Park",
        departureBuilding: "Burnham Lake",
        departureDate: new Date("2024-11-18"),
        departureTime: "8:00 PM",
        departureReturnDate: new Date("2024-11-21"),
        departureAddInformation: "Family vacation",
        contactCompanyName: "Private",
        contactPerson: "Alex Cruz",
        contactEmail: "alex.cruz@gmail.com",
        contactNumber: "+639556677889",
        deleted: false
    }
];

module.exports = sampleFormData;
